-- MySQL Script generated by MySQL Workbench
-- Mon Feb 15 23:48:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_farmacia_do_bem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_farmacia_do_bem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_farmacia_do_bem` DEFAULT CHARACTER SET utf8 ;
USE `db_farmacia_do_bem` ;

-- -----------------------------------------------------
-- Table `db_farmacia_do_bem`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_farmacia_do_bem`.`categoria` (
  `id_categoria` INT NOT NULL,
  `Setor` VARCHAR(45) NOT NULL,
  `Manipulação` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_farmacia_do_bem`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_farmacia_do_bem`.`produto` (
  `id_produto` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Preço` DOUBLE NOT NULL,
  `Estoque` TINYINT NOT NULL,
  `categoria_id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_produto`, `categoria_id_categoria`),
  INDEX `fk_produto_categoria_idx` (`categoria_id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_produto_categoria`
    FOREIGN KEY (`categoria_id_categoria`)
    REFERENCES `db_farmacia_do_bem`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
